"""add_category_and_image_url_to_product

Revision ID: fe9d65949d33
Revises: 6677b5ab780a
Create Date: 2026-01-15 23:24:37.207914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fe9d65949d33'
down_revision: Union[str, Sequence[str], None] = '6677b5ab780a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_name'), 'build', ['name'], unique=False)
    op.create_table('builditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builditem_category'), 'builditem', ['category'], unique=False)
    op.add_column('product', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_column('product', 'image_url')
    op.drop_column('product', 'category')
    op.drop_index(op.f('ix_builditem_category'), table_name='builditem')
    op.drop_table('builditem')
    op.drop_index(op.f('ix_build_name'), table_name='build')
    op.drop_table('build')
    # ### end Alembic commands ###
